# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f9a508c3f8acf7e5eba1e104d5c25ac916e45d37204801450c9e9363bd96ce6501a7d44252ab418a872d7be2c7d5c93a3eeba9883c8d21f31fad2c9dafac930

test:
  secret_key_base: 2dad0ff38854ca34cabbf5386f13adf2216a30e765de375f2af7d32d4c21dfe13eac0cf00c04d79ad9879222c3dd758e2914b64784f4840ceba2eb40c8b4bdc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
